name: 'ioBroker Testing: check and lint'
author: 'AlCalzone'
#description: 'Greet someone'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
  type-checking:
    description: 'Set to true when the adapter should be type-checked'
    default: 'false'
  type-checking-command:
    description: 'Overwrite the default type checking command'
    default: 'npm run build:ts -- --noEmit'
  lint:
    description: 'Set to true when the adapter has a linter configured'
    default: 'false'
  lint-command: 
    description: 'Overwrite the default lint command'
    default: 'npm run lint'

# Conditional syntax isn't supported, but there are workarounds:
# https://github.com/actions/runner/issues/834#issuecomment-909921245

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Perform a type check
      shell: bash
      run: |
        if ${{ inputs.type-checking }}; then
          ${{ inputs.type-checking-command }}
        else
          echo "Skipping type check..."
        fi

    - name: Lint source code
      shell: bash
      run: |
        if ${{ inputs.lint }}; then
          ${{ inputs.lint-command }}
        else
          echo "No linter configured, skipping..."
        fi

    - name: Test package files
      shell: bash
      run: npm run test:package
