name: 'ioBroker Testing: check and lint'
author: 'AlCalzone'
#description: 'Greet someone'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
  typescript:
    description: 'Set to true when this is a TypeScript adapter'
    default: 'false'
  lint:
    description: 'Set to true when the adapter has a linter configured'
    default: 'false'

# Conditional syntax isn't supported, but there are workarounds:
# https://github.com/actions/runner/issues/834#issuecomment-909921245

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Perform a type check
      shell: bash
      run: |
        if ${{ inputs.typescript }}; then
          npm run build:ts -- --noEmit
        else
          echo "Not TypeScript, skipping type check..."
        fi

    - name: Lint source code
      shell: bash
      run: |
        if ${{ inputs.lint }}; then
          npm run lint
        else
          echo "No linter configured, skipping..."
        fi

    - name: Test package files
      shell: bash
      run: npm run test:package
